name: Build, Release, and Deploy

on:
  push:
    branches: [main]

env:
  APP_NAME: Quizlone

jobs:
  build_android:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.get_version.outputs.app_version }}
    steps:
      - uses: actions/checkout@v5
      - name: Decode and Create Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/upload-keystore.jks
      - name: Create key.properties File
        run: |
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=../upload-keystore.jks" >> android/key.properties
      - uses: actions/setup-java@v5
        with: { distribution: "temurin", java-version: "17" }
      - uses: subosito/flutter-action@v2
        with: { channel: "stable", cache: true }
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
      - name: Extract App Version
        id: get_version
        run: |
          fullVersion=$(grep -m1 '^version:' pubspec.yaml | sed 's/version: *//')
          cleanVersion=$(echo "$fullVersion" | cut -d+ -f1)
          echo "app_version=$cleanVersion" >> $GITHUB_OUTPUT
          echo "Detected full version: $fullVersion"
          echo "Using sanitized version for release: $cleanVersion"
      - name: Prepare APKs for Release
        run: |
          find build/app/outputs/apk/release -name "*x86_64*.apk" -delete
          cd build/app/outputs/apk/release
          shopt -s nullglob
          for file in app-*-release.apk; do
            arch=$(echo "$file" | sed -e 's/app-//' -e 's/-release.apk//')
            new_name="${{ env.APP_NAME }}-${arch}.apk"
            mv "$file" "$new_name"
          done
      - uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: build/app/outputs/apk/release/*.apk

  create_release:
    runs-on: ubuntu-latest
    needs: [build_android]
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R artifacts
      - name: Create Draft Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            artifacts/**/*.apk
          draft: true
          allowUpdates: true
          tag: "dev-build-${{ github.run_number }}"
          name: "Version ${{ needs.build_android.outputs.app_version }}"
          body: |
            Automated development build.
            Triggered by commit: `${{ github.sha }}`
